apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: smartquaildb
data:
  POSTGRES_DB: QND41STGDB
  POSTGRES_USER: sqadmindb
  POSTGRES_PASSWORD: smartquaildev1719pass



 
 
  
 
