# Generated by Django 3.2.5 on 2021-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210715_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CI',
            field=models.BigIntegerField(max_length=10, null=True, verbose_name='Identy ID'),
        ),
    ]
