# Generated by Django 3.2.5 on 2021-10-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CI',
            field=models.BigIntegerField(max_length=13, null=True, verbose_name='Identy ID'),
        ),
    ]
