# Generated by Django 3.2.5 on 2021-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_deployd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cloud_server',
            field=models.CharField(choices=[('AWS Cloud', 'AWS Cloud'), ('Digital Ocean', 'Digital Ocean'), ('Microsoft Azure', 'Microsoft Azure'), ('Google Cloud', 'Google Cloud'), ('SmartQuail Cloud', 'SmartQuail Cloud')], max_length=50, null=True, verbose_name='Cloud Servers'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Project_name'),
        ),
    ]
