# Generated by Django 3.2.5 on 2021-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211022_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address_cloud',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
