# Generated by Django 3.2.5 on 2021-10-22 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='IVA',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
