# Generated by Django 3.2.5 on 2021-10-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serices_types',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=20, null=True),
        ),
    ]
