# Generated by Django 3.2.5 on 2021-10-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_acuerdoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdoitem',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acuerdo_items', to='contracts.contract'),
        ),
    ]
