# Generated by Django 3.2.5 on 2021-10-18 20:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_acuerdoitem_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
