# Generated by Django 3.2.5 on 2021-10-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractitem_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Business_type',
            field=models.CharField(choices=[('Company', 'compañia'), ('Negocio', 'negocio')], max_length=20, null=True, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Cli_title',
            field=models.CharField(choices=[('Sr', 'Señor.'), ('Ing', 'Ingeniero'), ('Arq', 'Arquitecto'), ('Lic', 'Licenciado'), ('Phd', 'Doctor')], max_length=20, null=True, verbose_name='Title Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Law_type',
            field=models.CharField(choices=[('JURIDICO', 'legalmente'), ('NATURAL', 'Naturalmente')], max_length=20, null=True, verbose_name='Law Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('ACUERDO', 'Acuerdo de confidencialidad y privacidad de datos'), ('CONTRATO_1', 'Contrato de Servicios de Tecnologias de Información (IT)')], max_length=200, null=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first names'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last names'),
        ),
    ]
