# Generated by Django 3.2.5 on 2021-10-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20211019_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Business_name',
            field=models.CharField(max_length=100, null=True, verbose_name='first names'),
        ),
    ]
