# Generated by Django 3.2.5 on 2021-10-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Business_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Business names'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('Acuerdo de confidencialidad y privacidad de datos', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_1')], max_length=200, null=True, verbose_name='Contract Type'),
        ),
    ]
