# Generated by Django 3.2.5 on 2021-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20211019_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractitem',
            name='intro',
        ),
        migrations.AddField(
            model_name='acuerdoitem',
            name='clausura',
            field=models.CharField(max_length=250, null=True, verbose_name='clausura'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Business_type',
            field=models.CharField(choices=[('company', 'compañia'), ('negocio', 'negocio')], max_length=20, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Law_type',
            field=models.CharField(choices=[('Juridicamente ', 'JURIDICO'), ('Naturalmente ', 'NATURAL')], max_length=20, null=True, verbose_name='Law Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('Acuerdo de confidencialidad y privacidad de información', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_1')], max_length=200, null=True, verbose_name='Contract Type'),
        ),
    ]
