# Generated by Django 4.1.2 on 2022-10-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20211019_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Business_type',
            field=models.CharField(choices=[('compañia', 'compañia'), ('negocio', 'negocio')], max_length=20, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Cli_title',
            field=models.CharField(choices=[('Sr', 'Señor.'), ('Sra', 'Señora.'), ('Sta', 'Señorita.'), ('Ing', 'Ingeniero'), ('Arq', 'Arquitecto'), ('Lic', 'Licenciado'), ('Phd', 'Doctor')], max_length=20, null=True, verbose_name='Title Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('Acuerdo de confidencialidad y privacidad de información', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_1'), ('Contrato de Servicios de Consultoria en el departamento de gerencia', 'CONTRATO_CG')], max_length=200, null=True, verbose_name='Contract Type'),
        ),
    ]
