[uwsgi]
#socket=:9999
http  = 0.0.0.0:9999
virtualenv =/Users/smarquaildev/Desktop/QNODES_DEV/qnode4.1_app/qnode4.1_venv/
env=DJANGO_SETTINGS_MODULE=qnode41_app.settings
chdir = /Users/smarquaildev/Desktop/QNODES_DEV/qnode4.1_app/qnode41_app/
base =  /Users/smarquaildev/Desktop/QNODES_DEV/qnode4.1_app/qnode41_app/
wsgi-file = qnode41_app/wsgi.py 
processes = 10
threads = 2
vacuum = True
harakiri=200
stats = 0.0.0.0:8000
safe-pidfile = %(base)/celery.pid
smart-attach-daemon =  %(base)celery.pid %(virtualenv)/bin/celery -A qnode41_app  worker --pidfile=%(base)celery.pid
#daemonize = /path/to/djangapp/logs/CustomerCare-@(exec://date +%%Y-%%m-%%d).log
#log-reopen = true
buffer-size = 32768