# Generated by Django 3.2.16 on 2022-12-07 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_en_orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admininout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(choices=[('AP', 'ADRIAN PETROLEUM SERVICES S.A'), ('CDB', 'CENTRO DE DISEÑO Y DECORACIÓN EL BOSQUE'), ('ASM', 'CONJUNTO ALCAZAR DE SALAMANCA'), ('CHS', 'CONJUNTO HABITACIONAL SIERRA I Y II'), ('CSM', 'CONJUNTO SAN MARTÍN'), ('CS', 'CONJUNTO SIRAH'), ('VC', 'CONJUNTO VALLE CARTAGO'), ('VMU', 'CONJUNTO VIA MARINA UNO'), ('PZT', 'EDIFICIO PIAZZA TOSCANA'), ('APZ', 'EDIFICIO ARISTO PLAZA'), ('AL', 'EDIFICIO ASIEL'), ('ASP', 'EDIFICIO ASPEN'), ('BTP', 'EDIFICIO BATAN PLAZA'), ('BZ', 'EDIFICIO BIZANCIO'), ('BD', 'EDIFICIO BLUE DIAMOND II'), ('BT', 'EDIFICIO BRISTOL TORRE II'), ('CC', 'EDIFICIO CAMPUS CENTRAL'), ('CB', 'EDIFICIO CORYBA'), ('PD', 'EDIFICIO EL PEDREGAL'), ('FS', 'EDIFICIO FOUR SEASONS I'), ('KN', 'EDIFICIO KORONI'), ('KS', 'EDIFICIO KOUROS'), ('LG', 'EDIFICIO LAFARGUE'), ('MN', 'EDIFICIO METROPOLITAN'), ('PD', 'EDIFICIO PLUS DOS CENTRO DE NEGOCIOS'), ('PS', 'EDIFICIO PUERTAS DEL SOL'), ('SL', 'EDIFICIO SCALA '), ('SG', 'EDIFICIO SOHO GALAXY'), ('SR', 'EDIFICIO SORELINA'), ('TB', 'EDIFICIO TENIS BOULEVARD'), ('TA', 'EDIFICIO TERRAZAS ATRIUM'), ('TC', 'EDIFICIO TORRE CARE'), ('TF', 'EDIFICIO TORRE FINLANDIA'), ('TS', 'EDIFICIO TORRE SOL I'), ('TR', 'EDIFICIO TRIER'), ('VR', 'EDIFICIO VERONES'), ('VN', 'EDIFICIO VIENA'), ('AQ', 'FIDEICOMISO INMOBILIARIO PARK QUITO'), ('HD', 'AGENCIA HOMEDETAIL'), ('KZ', 'EDIFICIO KENZE'), ('CP', 'LA CASA EN EL PARQUE'), ('NS', 'EDIFICIO NOVAK STATUS'), ('PN', 'EDIFICIO PRISMA NORTE'), ('CS', 'CRISTIAN SILVA DOMINGUEZ'), ('VN', 'EDIFICIO TORRE DEL SOL'), ('TN', 'EDIFICIO TORRE NOHA')], max_length=4, verbose_name='Edificio')),
                ('ingreso', models.DateTimeField(null=True, verbose_name='Ingreso')),
                ('salida', models.DateTimeField(null=True, verbose_name='Salida')),
                ('novedades', models.TextField(blank=True, verbose_name='Novedades')),
                ('Observaciones', models.TextField(blank=True, verbose_name='Novedades')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada & Salida',
                'verbose_name_plural': 'Entradas & Salidas',
            },
        ),
    ]
