apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: postgres
  labels:
    app: pgadmin
spec:
 ports:
 - protocol: TCP
   port: 8090
   targetPort: http
 selector:
   app: pgadmin
 type: NodePort